// <auto-generated />
namespace S00015630Rad2017Mvc1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dateJoined : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dateJoined));
        
        string IMigrationMetadata.Id
        {
            get { return "201710271036296_dateJoined"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
